export const GUI_LABELS = {
  en: {
    language: "Language",
    gameMode: "Game Mode",
    currentPlayer: "Current Turn",
    player1Group: "Player 1 Group",
    player2Group: "Player 2 Group",
    player1Score: "Player 1 Balls",
    player2Score: "Player 2 Balls",
    ballPhysics: "Ball Physics",
    strikeAngle: "Strike Angle",
    shotStrength: "Initial Impulse",
    cueOffsetHorizontal: "Cue Offset X (English)",
    cueOffsetVertical: "Cue Offset Y (Draw/Top)",
    strikeBall: "Strike Ball",
    currentVelocity: "Current Velocity",
    ballProperties: "Ball Properties",
    ballRadius: "Ball Radius",
    ballDensity: "Ball Density",
    ballRoughness: "Ball Friction",
    ballRestitution: "Ball Restitution",
    currentMass: "Current Mass (kg)",
    tableProperties: "Table Properties",
    floorFriction: "Floor Friction",
    tablePhysics: "Table Physics",
    restitution: "Restitution",
    wallFriction: "Wall Friction",
  },
  ar: {
    language: "اللغة",
    gameMode: "وضع اللعبة",
    currentPlayer: "الدور الحالي",
    player1Group: "مجموعة اللاعب 1",
    player2Group: "مجموعة اللاعب 2",
    player1Score: "كرات اللاعب 1",
    player2Score: "كرات اللاعب 2",
    ballPhysics: "فيزياء الكرة",
    strikeAngle: "زاوية الضربة",
    shotStrength: "قوة الضربة",
    cueOffsetHorizontal: "إزاحة المضرب الأفقية",
    cueOffsetVertical: "إزاحة المضرب العمودية",
    strikeBall: "اضرب الكرة",
    currentVelocity: "السرعة الحالية",
    ballProperties: "خصائص الكرة",
    ballRadius: "نصف قطر الكرة",
    ballDensity: "كثافة الكرة",
    ballRoughness: "خشونة الكرة",
    ballRestitution: "مرونة الكرة",
    currentMass: "الكتلة الحالية (كغم)",
    tableProperties: "خصائص الطاولة",
    floorFriction: "احتكاك الأرضية",
    tablePhysics: "فيزياء الطاولة",
    restitution: "معامل الارتداد",
    wallFriction: "احتكاك الحواف",
  },
};

export const GUI_TOOLTIPS = {
  en: {
    language: "Switch between Arabic and English interface language.",
    gameMode: "Select game mode: Practice, Physics Test, or Normal 8-Ball.",
    currentPlayer: "Shows which player's turn it is.",
    player1Group: "Shows the group (solids/stripes) assigned to Player 1.",
    player2Group: "Shows the group (solids/stripes) assigned to Player 2.",
    player1Score: "Number of balls Player 1 has pocketed.",
    player2Score: "Number of balls Player 2 has pocketed.",
    strikeAngle: "Adjusts the horizontal direction of the shot in degrees.",
    shotStrength: "Increases the initial force applied to the cue ball; higher power means faster speed.",
    cueOffsetHorizontal: "Shifts the strike point left/right to apply side-spin (English), curving the ball after cushion impact.",
    cueOffsetVertical: "Shifts the strike point up/down to apply top-spin (follow) or back-spin (draw).",
    strikeBall: "Press to execute the shot with the current settings.",
    currentVelocity: "Displays the current speed of the cue ball in m/s.",
    ballRadius: "Changes the physical size of the balls. Larger radius increases volume and calculated mass.",
    ballDensity: "Higher density makes the ball heavier at the same size, increasing its momentum during collisions.",
    ballRoughness: "Controls the surface roughness. Higher values increase spinning friction and grip on other balls.",
    ballRestitution: "Controls bounce elasticity. 1 means a perfectly elastic collision (no energy loss between balls).",
    currentMass: "Shows the calculated mass of the ball based on radius and density.",
    floorFriction: "Higher values simulate a rougher cloth table, causing balls to decelerate and stop much faster.",
    restitution: "Controls cushion elasticity. Higher values make the rails bounce the balls back with more speed.",
    wallFriction: "Affects energy loss and angle deflection when a ball slides tightly against the cushions.",
  },
  ar: {
    language: "التبديل بين اللغة العربية والإنجليزية في واجهة المستخدم.",
    gameMode: "اختر وضع اللعبة: تدريب، اختبار فيزياء، أو بلياردو 8 كرات عادي.",
    currentPlayer: "يعرض أي لاعب دوره الآن.",
    player1Group: "يعرض المجموعة (المصمتة/المخططة) المخصصة للاعب 1.",
    player2Group: "يعرض المجموعة (المصمتة/المخططة) المخصصة للاعب 2.",
    player1Score: "عدد الكرات التي سجلها اللاعب 1 في الجيوب.",
    player2Score: "عدد الكرات التي سجلها اللاعب 2 في الجيوب.",
    strikeAngle: "تعديل اتجاه الضربة الأفقي بالدرجات حول الكرة.",
    shotStrength: "زيادة القوة الابتدائية المطبقة على الكرة؛ طاقة أعلى تعني سرعة انطلاق أكبر.",
    cueOffsetHorizontal: "إزاحة نقطة الضرب يميناً/يساراً لتوليد دوران جانبي، يغير مسار الكرة بعد اصطدامها بالبند.",
    cueOffsetVertical: "إزاحة نقطة الضرب لأعلى/أسفل لتوليد دوران أمامي (Follow) أو دوران خلفي عكسي (Draw).",
    strikeBall: "اضغط لتنفيذ الضربة بالإعدادات الحالية.",
    currentVelocity: "يعرض السرعة الحالية للكرة البيضاء بالمتر/الثانية.",
    ballRadius: "تغيير الحجم الفيزيائي للكرات. القطر الأكبر يزيد الحجم والكتلة المحسوبة تلقائياً.",
    ballDensity: "الكثافة الأعلى تجعل الكرة أثقل لنفس الحجم، مما يزيد من كمية الحركة (الزخم) عند التصادم.",
    ballRoughness: "التحكم في خشونة السطح. القيم الأعلى تزيد من احتكاك الدوران والتماسك بين الكرات.",
    ballRestitution: "معامل ارتداد الكرات. القيمة 1 تعني تصادم مرن مثالي (دون أي فقدان في الطاقة بين الكرات).",
    currentMass: "يعرض الكتلة المحسوبة للكرة بناءً على نصف القطر والكثافة.",
    floorFriction: "القيم الأعلى تحاكي قماشاً خشناً للطاولة، مما يجعل الكرات تتباطأ وتتوقف بشكل أسرع.",
    restitution: "معامل ارتداد جدران الطاولة (البند). القيم الأعلى تجعل الجدار يرد الكرة بقوة وسرعة أكبر.",
    wallFriction: "يؤثر على فقدان الطاقة وانحراف زاوية الارتداد عندما تنزلق الكرة بمحاذاة جدران الطاولة.",
  }
};