export const GUI_LABELS = {
  en: {
    language: "Language",
    ballPhysics: "Ball Physics",
    strikeAngle: "Strike Angle",
    shotStrength: "Initial Impulse",
    cueOffsetHorizontal: "Cue Offset X (English)",
    cueOffsetVertical: "Cue Offset Y (Draw/Top)",
    strikeBall: "Strike Ball",
    currentVelocity: "Current Velocity",
    ballProperties: "Ball Properties",
    ballRadius: "Ball Radius",
    ballDensity: "Ball Density",
    ballRoughness: "Ball Friction",
    ballRestitution: "Ball Restitution",
    currentMass: "Current Mass (kg)",
    tableProperties: "Table Properties",
    floorFriction: "Floor Friction",
    tablePhysics: "Table Physics",
    restitution: "Restitution",
    wallFriction: "Wall Friction",
  },
  ar: {
    language: "اللغة",
    ballPhysics: "فيزياء الكرة",
    strikeAngle: "زاوية الضربة",
    shotStrength: "قوة الضربة",
    cueOffsetHorizontal: "إزاحة المضرب الأفقية",
    cueOffsetVertical: "إزاحة المضرب العمودية",
    strikeBall: "اضرب الكرة",
    currentVelocity: "السرعة الحالية",
    ballProperties: "خصائص الكرة",
    ballRadius: "نصف قطر الكرة",
    ballDensity: "كثافة الكرة",
    ballRoughness: "خشونة الكرة",
    ballRestitution: "مرونة الكرة",
    currentMass: "الكتلة الحالية",
    tableProperties: "خصائص الطاولة",
    floorFriction: "احتكاك الأرضية",
    tablePhysics: "فيزياء الطاولة",
    restitution: "معامل الارتداد",
    wallFriction: "احتكاك الحواف",
  },
};
